### ISSUE TITLE
ReactiveSearch is now requiring Vue.js dependency

### ISSUE THREAD

**Issue by iseabock** [appbaseio/reactivecore#20]
Not sure if I should post this here or on the ReactiveSearch repo.

I have had ReactiveSearch running great. Two days ago I started getting errors because it is requiring Vue.js as a dependency. I'm using this on a React app, and though I have things working now that I have installed Vue, but I really don't want to have to include Vue unnecessarily.

Can someone explain why Vue is a dependency

**Comment by metagrover** [comment]
@bietkul I think, it's because you added vue-types in `reactivecore` - https://github.com/appbaseio/reactivecore/blob/master/package.json#L31

We need a better abstraction for `types` if that's the case.

**Comment by bietkul** [comment]
Fixed it https://github.com/appbaseio/reactivecore/commit/aaf4b50140336d2bd5b987d28a4c5ac26217dd99

**Comment by bpkennedy** [comment]
This is still an issue in ^0.10.0 and for ^0.6.1 it was an issue but with the 'redux' module.

I see this in the iOS simulator after trying to build with 0.10.0:
```
"unable to resolve module 'vue' from ...../node_modules/vue-types/dist/utils.js. Module 'vue' does not exist in the Haste module map."
```

My package.json is this:
```
{
  "name": "dw-client",
  "version": "1.0.4",
  "engines": {
    "node": "10.0.0"
  },
  "files": [
    "dist"
  ],
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "dependencies": {
    "@appbaseio/reactivesearch-native": "^0.6.1",
    "@expo/ex-navigation": "^4.2.0",
    "axios": "^0.18.0",
    "expo": "^31.0.2",
    "mobx": "^5.6.0",
    "mobx-react": "^5.4.2",
    "prop-types": "^15.6.2",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-31.0.0.tar.gz",
    "styled-components": "^4.1.2"
  },
  "devDependencies": {
    "@babel/plugin-proposal-export-namespace-from": "^7.0.0",
    "babel-preset-expo": "^5.0.0"
  }
}
```

As the OP asked - why is Vue* in the dependency chain for the React Native library?  How do I get around this?  I'm a couple hours into troubleshooting this on my own already and about to give up pick another library.

**EDIT**:  It appears that ^0.9.0 of `reactivesearch-native` does not have this issue.  I guess I'll roll with that until this is working.

**Comment by metagrover** [comment]
@bpkennedy The bug is related to the `reactivesearc-native` package. We need to do a release that points to the updated reactivecore here.
